web/data/urls.py
from django.urls import path
from . import views

app_name = 'data'
urlpatterns = [
    path('', views.index, name='index'),
    path('upload/', views.upload, name='upload'),
    path('display/<int:id>/', views.display, name='display')
]

web/home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
]

web/synth/urls.py
from django.urls import path
from . import views

app_name = 'synth'
urlpatterns = [
    path('', views.index, name='index'),
    path('upload/', views.upload, name='upload'),
    path('programs/<int:id>/', views.programs, name='programs')
]

web/web/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import settings

urlpatterns = [
    path('dist/', include('dist.urls')),
    path('synth/', include('synth.urls')),
    path('data/', include('data.urls')),
    path('home/', include('home.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/home/', permanent=True)),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/data/models.py
from django.db import models


class Chart(models.Model):
    file_name = models.CharField(max_length=200)

    def __str__(self):
        return self.file_name


# Create your models here.

web/home/models.py
from django.db import models

# Create your models here.

web/polls/forms.py
from django.forms import *
from .models import *
from django.urls import reverse


class InstanceForm(ModelForm):
    file_field = forms.FileField(required=True, widget=ClearableFileInput(attrs={'multiple': True}))
    input_constraints = CharField(required=True)
    interaction_model = CharField(required=True)

web/data/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from .models import Chart
import ast
from django.shortcuts import render, get_object_or_404


# Create your views here.

def index(request):
    return render(request, 'data.html')


def upload(request):
    from .src.predict import chart_to_table
    res = None
    for file_name in list(request.FILES.keys()):
        f = request.FILES[file_name]
        res = chart_to_table(f, int(request.POST['min']), int(request.POST['max']))
        chart = Chart(id=None, file_name=file_name)
        chart.save()
        with open(f'extracted_csv_{chart.id}.csv', 'a+') as f:
            f.write(str(res))
        return HttpResponse(reverse('data:display', args=(chart.id,)))


def display(request, id):
    chart = get_object_or_404(Chart, pk=id)
    with open(f'extracted_csv_{chart.id}.csv', 'r+') as f:
        res = ast.literal_eval(f.read())
    return render(request, 'data_display.html', {
        "header": ['COL0', 'COL1'], "rows": [[f'bar{i}', f'{res[1][i]:.4f}'] for i in range(res[0])]
    })

web/home/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request, 'home.html')

web/synth/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
import ast
from django.shortcuts import render, get_object_or_404

# Create your views here.


def index(request):
    return render(request, 'synthesizer.html')


def upload(request):
    return HttpResponseRedirect(reverse('synth:programs', args=(1,)))


def programs(request, id):
    return render(request, 'programs.html', {
        "programs": ['COL0', 'COL1']
    })

web/data/templates/data.html
{% extends 'base.html' %}

{% block content %}

<style>
    #myDropzone {
        cursor: pointer;
        border: 0.1em dashed rgba(0, 0, 0, 0.5);
    }

    .dz-message {
        padding: 40px;
    }

    .dropzone .dz-preview .dz-image {

    }

    .dz-progress {
        /* progress bar covers file name */
        display: none !important;
    }

    @media (min-width: 768px) {
        #rude {
            width: 70%;
        }
    }

    @media (min-width: 1920px) {
        #rude {
            width: 70%;
        }
    }

</style>

<script>
    Dropzone.options.myDropzone = {
        // Prevents Dropzone from uploading dropped files immediately
        autoProcessQueue: false,
        acceptedFiles: ".png, .jpg",
        parallelUploads: 1,
        addRemoveLinks: true,
        maxFilesize: 1, // MB
        url: "/unchartit" + "{% url 'data:upload' %}",
        init: function () {
            let submitButton = document.querySelector("#submit-all")
            myDropzone = this; // closure

            submitButton.addEventListener("click", function () {
                myDropzone.processQueue();
                // autoProcessQueue: true// Tell Dropzone to process all queued files.
            });

            // You might want to show the submit button only when
            // files are dropped here:
            this.on("addedfile", function () {
                submitButton.classList.remove("disabled");
            });

            this.on("complete", function (file) {
                if (this.getUploadingFiles().length === 0 && this.getQueuedFiles().length === 0) {
		        window.location.replace('/unchartit' + file.xhr.response)
                }
            });

            this.on("sending", function (file, xhr, data) {
                document.querySelector("#loading").hidden = false;
                let min = document.querySelector("#minval");
                let max = document.querySelector("#maxval");
                data.append("max", max.value);
                data.append("min", min.value);
            });

        }
    };
</script>


<div class="jumbotron" style="margin-bottom: 0px; padding-bottom:0px; background-color: white !important;">
    <div class="container-fluid" id="rude">
        <h4 style="font-weight: 500;">Data Extraction</h4>
        <hr>
        <ul>
            <li style="font-size: 100%; text-align: justify" class="mt-1"> In the data extraction step,
                <span style="font-variant: small-caps; font-weight: 600">UnchartIt</span> automatically extracts data from a chart.
            </li>
            <li style="font-size: 100%; text-align: justify" class="mt-1">
                Currently, <span style="font-variant: small-caps; font-weight: 600">UnchartIt</span> can only interpret bar charts.
                The user needs to provide the <b>min</b> & <b>max</b> values of the vertical axis.
            </li>
            <li style="font-size: 100%; text-align: justify" class="mt-1">
		{% load static %}
		Download some <a href="{% static 'charts.tar.gz' %}">bar chart examples here</a>.
            </li>
        </ul>
    </div>
</div>



<div class="container">
    <div style="padding-bottom: 50px" class="row">
    </div>
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <div class="form-row">
                <div class="form-group col-md-3">
                    <label>Vertical Axis</label>
                    <input class="form-control" type="text" value="Values" readonly>
                    </select>
                </div>
                <div class="col-md-1"></div>
                <div class="form-group col-md-4">
                    <label>Min Value</label>
                    <input value="0" id="minval" class="form-control" type="number">
                </div>
                <div class="form-group  col-md-4">
                    <label>Max Value</label>
                    <input value="128" id="maxval" class="form-control" type="number">
                </div>
            </div>
        </div>
        <div class="col-md-3"></div>

    </div>
    <div class="row">
        <div class="col-md-3"></div>

        <div class="col-md-6">

            <div class="form-group">
                <div id='myDropzone' name='dropzone' class='dropzone'>
                    <div class="dz-message" data-dz-message><span>Drop the chart here.</span></div>
                </div>
            </div>
            <div class="form-group">
                <button type="button" style="float: right;" id="submit-all" class="btn btn-primary disabled">
                    Submit
                    <span id="loading" class="spinner-border spinner-border-sm" role="status" aria-hidden="true"
                          hidden></span>
                </button>
            </div>


        </div>
        <div class="col-md-3"></div>
    </div>
</div>


{% endblock %}

web/data/templates/data_display.html
{% extends 'base.html' %}

{% block content %}
<section style="background-color: white" class="jumbotron text-center">
    <div class="container">
        <h4 class="jumbotron-heading">Table extracted from the chart:</h4>
        <br>
        <div class="justify-content-center" style="width: 75%; margin: auto; display: flex;">
            <table style="align-self: center; text-align: center;"
                   class="table table-striped table-hover table-bordered table-responsive table-fit">
                <thead class="thead-dark">
                <tr>
                    {% for k in header %}
                    <th>{{k}}</th>
                    {% endfor %}
                </tr>
                </thead>
                <tbody>
                {% for r in rows %}
                <tr>
                    {% for c in r %}
                    <td>{{c}}</td>
                    {% endfor %}
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</section>
{% endblock %}

web/home/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'dropzone/min/dropzone.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="{% static 'dropzone/min/dropzone.min.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            crossorigin="anonymous"></script>
    <title>UnchartIt</title>
</head>

<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <a style="font-variant: small-caps;" class="navbar-brand" href="/">UnchartIt</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#components"
            aria-controls="components" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="components">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="/data/">Data Extraction <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/synth/">Synthesizer <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/dist/">Distinguisher <span class="sr-only">(current)</span></a>
            </li>
        </ul>
    </div>
</nav>
{% block content %}{% endblock %}
</body>

<footer class="text-muted">
    <div class="container">
        <hr>
        <div class="row">
            <div class="col-md-7 my-auto">
                <p>The source code is made available on <a href="/">GitHub</a> under some license.</p>
                <p>To contact the authors please send an email to: <a href="mailto:unchartit@sat.inesc-id.pt">unchartit@sat.inesc-id.pt</a>
                </p>
            </div>
            <div class="col-md-5 d-flex justify-content-around align-items-center">
                <p>
		    <img style="width: 125px;" class="img-fluid" src="{% static 'inesc.png' %}"/>
                </p>
                <p>
		    <img style="width: 100px" class="img-fluid" src="{% static 'fct.png' %}"/>
                </p>
            </div>
        </div>
    </div>
</footer>
</html>

web/home/templates/home.html
{% extends 'base.html' %}
{% block content %}

<style>
    @media (min-width: 768px) {
        #rude {
            width: 70%;
        }
    }

    @media (min-width: 1920px) {
        #rude {
            width: 70%;
        }
    }

    @media (orientation: landscape) {
        #pipeline {
            display: block !important;
        }
        #pipeline_vertical {
            display: none !important;
        }
    }

    @media (orientation: portrait) {
        #pipeline {
            display: none !important;
        }
        #pipeline_vertical {
            display: block !important;
        }
    }

    .icons {
        text-align: right;
    }
    .icons a {
        color: rgba(0, 0, 0, .6);
        text-decoration: none;
    }

    ul.icons {
        cursor: default;
        list-style: none;
        padding-right: 0;
    }

    ul.icons li {
        display: inline-block;
        padding: 0 1em 0 0;
        font-size: 120%;
        font-weight: bold;
    }

    ul.icons li:last-child {
        padding-right: 0 !important;
    }

    ul.icons li .icon:before {
        font-size: 1.25em;
    }

    ul.icons li span {
        display: inline-block;
        padding: 0 0 0 .5em;
        font-size: 80%;
        font-family: Merriweather, sans-serif;
        font-weight: normal;
    }
</style>

<main role="main">

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
        <div class="container-fluid" id="rude">
            <h1 style="font-variant: small-caps; font-weight: 600" class="display-5">UnchartIt</h1>
            <h5 style="font-weight: 300; color: #404040;">An Interactive Framework for Program Recovery from Charts</h5>
            <hr>
            <p style="font-size: 100%; text-align: justify" class="mt-5"><span style="font-variant: small-caps;">UnchartIt</span>
                is the first program synthesizer
                to recover data transformations from chart images.
                Given an input table and a chart, <span style="font-variant: small-caps;">UnchartIt</span>
                automatically recovers the data transformations
                in four steps: data extraction,
                candidate generation, candidate ranking, and candidate disambiguation.</p>

            <p style="font-size: 0.9em" class="mt-5">
                <span style="font-weight: 600">Authors</span>: Daniel Ramos, Jorge Pereira, Inês Lynce, Vasco Manquinho,
                Ruben Martins
            </p>
            <ul class="icons">
                <li>
                    <a href="https://github.com/danieltrt/Distinguisher" class="fa fa-file">
                        <span>Paper</span>
                    </a>
                </li>
                <li>
                    <a href="https://github.com/danieltrt/Distinguisher" class="fa fa-github">
                        <span>Source Code</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="container">
	    {% load static %}
	    <img id="pipeline" class="img-fluid mx-auto d-block" src="{% static 'horizontal.png' %}"/>
	    <img id="pipeline_vertical" class="img-fluid mx-auto d-block" src="{% static 'vertical.png' %}"/>
    </div>
</main>

{% endblock %}

web/polls/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'dropzone/min/dropzone.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'dropzone/min/dropzone.min.js' %}" ></script>
    <title>UnchartIt</title>
</head>

<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <a style="font-variant: small-caps;" class="navbar-brand" href="#">UnchartIt</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
        </ul>
    </div>
</nav>
{% block content %}{% endblock %}
</body>
</html>

web/polls/templates/success.html
{% extends 'base.html' %}

{% block content %}

<p>Success</p>

{% endblock %}

web/synth/templates/programs.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'css/rainbow-custom.min.css' %}">
<script src="{% static 'js/rainbow-custom.min.js' %}"></script>

<section style="background-color: white" class="jumbotron text-center">
    <div class="container h-100" style="width: 100%">
        <h4 class="jumbotron-heading">Best programs found:</h4>
        <br>
        {% for p in programs %}
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <div>
                    <pre><code data-language="c">{{p}}</code></pre>
                </div>
            </div>
            <div class="col-md-3"></div>
        </div>
        {% endfor %}
    </div>
</section>
{% endblock %}

web/synth/templates/synthesizer.html
{% extends 'base.html' %}

{% block content %}

<style>
    @media (min-width: 768px) {
        #rude {
            width: 70%;
        }
    }

    @media (min-width: 1920px) {
        #rude {
            width: 70%;
        }
    }
</style>

<script>
    let c = 0;

    function count() {
        c += 1;
        if (c >= 2) {
            let submitButton = document.querySelector("#submit-all")
            submitButton.classList.remove("disabled");
        }
    }

    window.onload = function () {
        document.querySelector("#input").onchange = count;
        document.querySelector("#output").onchange = count;
    }

    function enter_loading() {
        document.querySelector("#loading").hidden = false;
    }



</script>


<div class="jumbotron" style="margin-bottom: 0px; padding-bottom: 0px; background-color: white !important;">
    <div class="container-fluid" id="rude">
        <h4 style="font-weight: 500;">Program Synthesis</h4>
        <hr>
        <ul>
            <li style="font-size: 100%; text-align: justify" class="mt-1">
                After interpreting the chart, <span style="font-variant: small-caps; font-weight: 600">UnchartIt</span>
                needs to find a program that maps the input table into the desired output.
            </li>
            <li style="font-size: 100%; text-align: justify" class="mt-1">
                However, <span style="font-variant: small-caps; font-weight: 600">UnchartIt</span>
                doesn't have access to the desired output! Only an approximation, extracted in the previous step.
            </li>
            <li style="font-size: 100%; text-align: justify" class="mt-1">
                Download some <a href="">input-output examples here</a>.
            </li>
        </ul>
    </div>
</div>



<div class="container">
    <div style="padding-bottom: 50px" class="row">
    </div>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <form method="post" enctype="multipart/form-data" action="{% url 'synth:upload' %}" >
                <div class="form-row">
                    <div class="form-group col-md-3">
                        <label for="input">Input table:</label>
                        <input type="file" name="input" id="input"/>
                    </div>
                    <div class="form-group col-md-2"> </div>
                    <div class="form-group col-md-3">
                        <label for="output">Output table:</label>
                        <input type="file" name="output" id="output"/>
                    </div>
                    <div class="form-group col-md-4"> </div>
                </div>
                <div class="form-group col-md-12">
                    <button onclick="enter_loading()" type="submit" style="float: right;" id="submit-all" class="btn btn-primary disabled">
                        Submit
                        <span id="loading" class="spinner-border spinner-border-sm" role="status" aria-hidden="true"
                              hidden></span>
                    </button>
                </div>
            </form>
        </div>
        <div class="col-md-2"></div>
    </div>
</div>


{% endblock %}